### ISSUE TITLE
Memory/CPU limits

### ISSUE THREAD

**Issue by davidcurrie** [WASdev/ci.docker#112] opened 2017-03-17 15:02 UTC
Document/blog use of JAVA_OPTS environment variable on container to keep memory within bounds of container (c.f. https://dzone.com/articles/java-inside-docker-what-you-must-know-to-not-fail). Investigate option of script to set these intelligently.

**Comment by ernani** [comment] 2017-03-17 15:06
Damn, you are fast, I was about to let you know about that article! Awesome job!

**Comment by yiquanzhou** [comment] 2017-11-23 09:09
Hi, is it currently possible to configure the max heap size for the Liberty docker container by passing the environment variable `-e JAVA_OPTIONS='-Xmx300m'`? If not are you going to work on this feature? Thanks!

**Comment by davidcurrie** [comment] 2017-11-23 09:51
@yiquanzhou - the environment variable is JAVA_OPTS for Liberty but otherwise, yes, that should work.

**Comment by yiquanzhou** [comment] 2017-11-24 12:48
@davidcurrie I tried `docker run -d -e JAVA_OPTS='-Xmx1m' websphere-liberty` but I didn't get an OutOfMemory exception. Is this the way to pass the JAVA_OPTS to the liberty docker image?

**Comment by davidcurrie** [comment] 2017-11-27 10:21
@yiquanzhou - my apologies - it should by `JVM_ARGS`.

```
docker run -e JVM_ARGS='-Xmx1m' websphere-liberty
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2017/11/27 10:20:18 - please wait.
```

**Comment by yiquanzhou** [comment] 2017-11-28 09:26
@davidcurrie Yes that works! Thank you!

**Comment by lgrateau** [comment] 2018-05-23 08:31
The jdk 1.8 include dedicated flags for Docker. See the 
-XX:+UnlockExperimentalVMOptions 
XX:+UseCGroupMemoryLimitForHeap \
-XX:MaxRAMFraction=1 
that allow to manage automaticaly memory and cpu.
This flags are experimentals in the sun jvm. I don't know if this flags exists also in the IBM JVM.
 https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits
 https://bugs.openjdk.java.net/browse/JDK-8146115

In the jdk 10 java on docker will be correctly supported. 
Is it possible to move to jdk 10 or enable dedidated flags for jdk 8.

**Comment by arthurdm** [comment] 2018-05-29 20:13
@dinogun can probably comment if these flags are present in the IBM JVM.

**Comment by dinogun** [comment] 2018-05-30 11:31
IBMJava Java 8 SR5 FP16 slated for GA tomorrow will have Docker support. However FP16 will not have Docker support turned on by default, please use the ```-XX:+UseContainerSupport``` flag to do so. This will do the following
1. Recognize that the JVM is running in a container
2. Limit the max heap size to 75% of the container mem limit if any (Provided no -Xmx is set)

**Comment by lgrateau** [comment] 2018-05-30 15:05
Thanks,
Does this flags will be enabled by default in the docker image ?

**Comment by arthurdm** [comment] 2018-05-30 20:45
Interestingly enough, I tried the `-XX:+UseContainerSupport` flag in `SR5 FP15` and the JVM did not complain.

@dinogun - what's the recommended way to check if that flag is being honoured?

**Comment by lgrateau** [comment] 2018-06-07 13:32
We have perform internal bench and it's seems to compute correctly the memory.

**Comment by arthurdm** [comment] 2018-06-07 15:55
thanks for confirming @lgrateau!    Looks like we should definitely enable this into the container then.  I will leave this issue opened for this.  If anyone wants to submit a PR before I do, please feel free =)

**Comment by lgrateau** [comment] 2018-06-07 16:05
What we observe is that this flags is already take into account by the liberty runtime. We have used the latest docker image available in Dockehub to perform our tests. Thanks a lot for your help!

**Comment by dinogun** [comment] 2018-06-07 16:48
Sorry for not getting back on this sooner, actually we turned it on by default in the ibmjava docker image itself. ```https://github.com/ibmruntimes/ci.docker/blob/master/ibmjava/8/jre/ubuntu/Dockerfile```

The way to check this would be to run the docker image itself
```
$ docker run --rm -it -m8G ibmjava:sfj-alpine java -verbose:sizes -version
  -Xmca32K        RAM class segment increment
  -Xmco128K       ROM class segment increment
  -Xmcrs200M      compressed references metadata initial size
  -Xmns2M         initial new space size
  -Xmnx1536M      maximum new space size
  -Xms8M          initial memory size
  -Xmos6M         initial old space size
  -Xmox6G         maximum old space size
  -Xmx6G          memory maximum                                 ----> (75% of 8GB)
  -Xmr16K         remembered set size
  -Xlp:objectheap:pagesize=4K     large page size
                  available large page sizes:
                  4K
  -Xlp:codecache:pagesize=4K     large page size for JIT code cache
                  available large page sizes for JIT code cache:
                  4K
  -Xmso256K       operating system thread stack size
  -Xiss2K         java thread stack initial size
  -Xssi16K        java thread stack increment
  -Xss1M          java thread stack maximum size
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 8.0.5.16 - pxa6480sr5fp16-20180524_01(SR5 FP16) Small Footprint)
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180523_387150 (JIT enabled, AOT enabled)
OpenJ9   - c81abfb
OMR      - f3f8112
IBM      - 4f87eeb)
JCL - 20180515_01 based on Oracle jdk8u171-b11
```
@arthurdm Please note that the default behaviour for any -XX parameter that is not recognized by the JVM is to silently ignore it and so earlier JVM versions would do nothing with that flag.

**Comment by arthurdm** [comment] 2018-06-08 01:10
awesome, thanks a lot @dinogun!    So given that this is [turned on](https://github.com/ibmruntimes/ci.docker/blob/5e1141743177128d563646fcf9bc4413acf68fd1/ibmjava/8/jre/ubuntu/Dockerfile#L77) at the IBM Java image, we won't need to update our WebSphere Liberty images.   Closing this issue.

**Closed by arthurdm** 2018-06-08 01:10 UTC

**Comment by recena** [comment] 2018-10-09 08:14
@dinogun Helllo, I did the same using `ibmcom/websphere-traditional:8.5.5.14-profile` but the result is bit different:

```
$ docker run --rm -it -m10G ibmcom/websphere-traditional:8.5.5.14-profile /opt/IBM/WebSphere/AppServer/java/bin/java -verbose:sizes -version
  -Xmca32K        RAM class segment increment
  -Xmco128K       ROM class segment increment
  -Xmcrs200M      compressed references metadata initial size
  -Xmns2M         initial new space size
  -Xmnx128M       maximum new space size
  -Xms8M          initial memory size
  -Xmos6M         initial old space size
  -Xmox512M       maximum old space size
  -Xmx512M        memory maximum
  -Xmr16K         remembered set size
  -Xlp:objectheap:pagesize=4K	 large page size
                  available large page sizes:
                  4K
  -Xlp:codecache:pagesize=4K	 large page size for JIT code cache
                  available large page sizes for JIT code cache:
                  4K
  -Xmso256K       operating system thread stack size
  -Xiss2K         java thread stack initial size
  -Xssi16K        java thread stack increment
  -Xss1M          java thread stack maximum size
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 8.0.5.17 - pxa6480sr5fp17ifix-20180726_01(SR5 FP17+IJ08001))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180725_392885 (JIT enabled, AOT enabled)
OpenJ9   - a8cda37
OMR      - 4d1cb10
IBM      - 21870d6)
JCL - 20180619_01 based on Oracle jdk8u171-b11
```

`memory maximum` is always the same. No changes when I use `docker -m4GB`.

Do you have any idea? FTR, I'm investigating how I can tweak the memory settings on this IBM WAS docker image.

**Comment by dinogun** [comment] 2018-10-09 09:06
Checking what caused this regression in `pxa6480sr5fp17ifix-20180726_01(SR5 FP17+IJ08001))`. The latest image seems to work ok.
```
$ docker run --rm -it -m10G ibmjava java -verbose:sizes -version
  -Xmca32K        RAM class segment increment
  -Xmco128K       ROM class segment increment
  -Xmcrs200M      compressed references metadata initial size
  -Xmns2M         initial new space size
  -Xmnx1920M      maximum new space size
  -Xms8M          initial memory size
  -Xmos6M         initial old space size
  -Xmox7678M      maximum old space size
  -Xmx7680M       memory maximum
  -Xmr16K         remembered set size
  -Xlp:objectheap:pagesize=4K	 large page size
                  available large page sizes:
                  4K
  -Xlp:codecache:pagesize=4K	 large page size for JIT code cache
                  available large page sizes for JIT code cache:
                  4K
  -Xmso256K       operating system thread stack size
  -Xiss2K         java thread stack initial size
  -Xssi16K        java thread stack increment
  -Xss1M          java thread stack maximum size
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 8.0.5.22 - pxa6480sr5fp22-20180919_01(SR5 FP22))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180915_397057 (JIT enabled, AOT enabled)
OpenJ9   - 6c152c2
OMR      - 15647c3
IBM      - d734883)
JCL - 20180821_01 based on Oracle jdk8u181-b12
```

**Comment by dinogun** [comment] 2018-10-09 09:44
It looks like WAS Traditional image is not based on the ibmjava image and instead is being built from the OS image. It is not setting `-XX:+UseContainerSupport` in the Dockerfile which is why you are seeing this error. The following makes that clear
```
$ docker run --rm -it -m10G ibmcom/websphere-traditional:8.5.5.14-profile /bin/bash
was@b40a6ca28635:/$ /opt/IBM/WebSphere/AppServer/java/bin/java -verbose:sizes -version
  -Xmca32K        RAM class segment increment
  -Xmco128K       ROM class segment increment
  -Xmcrs200M      compressed references metadata initial size
  -Xmns2M         initial new space size
  -Xmnx128M       maximum new space size
  -Xms8M          initial memory size
  -Xmos6M         initial old space size
  -Xmox512M       maximum old space size          ## Container support not turned on here
  -Xmx512M        memory maximum
  -Xmr16K         remembered set size
  -Xlp:objectheap:pagesize=4K	 large page size
                  available large page sizes:
                  4K
  -Xlp:codecache:pagesize=4K	 large page size for JIT code cache
                  available large page sizes for JIT code cache:
                  4K
  -Xmso256K       operating system thread stack size
  -Xiss2K         java thread stack initial size
  -Xssi16K        java thread stack increment
  -Xss1M          java thread stack maximum size
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 8.0.5.17 - pxa6480sr5fp17ifix-20180726_01(SR5 FP17+IJ08001))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180725_392885 (JIT enabled, AOT enabled)
OpenJ9   - a8cda37
OMR      - 4d1cb10
IBM      - 21870d6)
JCL - 20180619_01 based on Oracle jdk8u171-b11
was@b40a6ca28635:/$
was@b40a6ca28635:/$ # Set the container support explicitly
was@b40a6ca28635:/$ export JAVA_TOOL_OPTIONS="-XX:+UseContainerSupport"
was@b40a6ca28635:/$
was@b40a6ca28635:/$ /opt/IBM/WebSphere/AppServer/java/bin/java -verbose:sizes -version
  -Xmca32K        RAM class segment increment
  -Xmco128K       ROM class segment increment
  -Xmcrs200M      compressed references metadata initial size
  -Xmns2M         initial new space size
  -Xmnx1920M      maximum new space size
  -Xms8M          initial memory size
  -Xmos6M         initial old space size
  -Xmox7680M      maximum old space size        ## Container support turned ON here
  -Xmx7680M       memory maximum
  -Xmr16K         remembered set size
  -Xlp:objectheap:pagesize=4K	 large page size
                  available large page sizes:
                  4K
  -Xlp:codecache:pagesize=4K	 large page size for JIT code cache
                  available large page sizes for JIT code cache:
                  4K
  -Xmso256K       operating system thread stack size
  -Xiss2K         java thread stack initial size
  -Xssi16K        java thread stack increment
  -Xss1M          java thread stack maximum size
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 8.0.5.17 - pxa6480sr5fp17ifix-20180726_01(SR5 FP17+IJ08001))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180725_392885 (JIT enabled, AOT enabled)
OpenJ9   - a8cda37
OMR      - 4d1cb10
IBM      - 21870d6)
JCL - 20180619_01 based on Oracle jdk8u171-b11
was@b40a6ca28635:/$ 
```

**Comment by dinogun** [comment] 2018-10-09 09:44
@arthurdm ^^

**Comment by dinogun** [comment] 2018-10-09 10:29
Do you have enough free mem where you are running this ? Can you try running it on a box that has lots of free mem.

**Comment by recena** [comment] 2018-10-09 10:54
@dinogun I've repeated the test by using `-m4G` and making sure that my physical memory has at least 6GB free.

**Comment by recena** [comment] 2018-10-09 11:09
@dinogun I think I'm seeing the expected results taking into account this:

```
was@0e11cbbd20b6:/$ ps -ef 
UID        PID  PPID  C STIME TTY          TIME CMD
was          1     0  0 10:59 pts/0    00:00:00 /bin/bash /work/start_server
was        483     1  7 10:59 pts/0    00:00:28 /opt/IBM/WebSphere/AppServer/jav
was        592     1  0 11:00 pts/0    00:00:00 tail -F /opt/IBM/WebSphere/AppSe
was        593     1  0 11:00 pts/0    00:00:00 tail -F /opt/IBM/WebSphere/AppSe
was        634     0  0 11:00 pts/1    00:00:00 /bin/bash
was       1019     1  0 11:06 pts/0    00:00:00 sleep 1
was       1020   634  0 11:06 pts/1    00:00:00 ps -ef
was@0e11cbbd20b6:/$ cat /proc/483/cmdline

/opt/IBM/WebSphere/AppServer/java/bin/java
-Dosgi.install.area=/opt/IBM/WebSphere/AppServer-Dwas.status.socket=39621
Dosgi.configuration.area=/opt/IBM/WebSphere/AppServer/profiles/AppSrv01/servers/server1/configuration-Djava.awt.headless=true
-Dosgi.framework.extensions=com.ibm.cds,com.ibm.ws.eclipse.adaptors
-Xshareclasses:name=webspherev85_1.8_64_bundled_%g,nonFatal-Dcom.ibm.xtq.processor.overrideSecureProcessing=true
-Xcheck:dump
-Djava.security.properties=/opt/IBM/WebSphere/AppServer/properties/java.security-Xbootclasspath/p:/opt/IBM/WebSphere/AppServer/java/jre/lib/ibmorb.jar-classpath/opt/IBM/WebSphere/AppServer/profiles/AppSrv01/properties:/opt/IBM/WebSphere/AppServer/properties:/opt/IBM/WebSphere/AppServer/lib/startup.jar:/opt/IBM/WebSphere/AppServer/lib/bootstrap.jar:/opt/IBM/WebSphere/AppServer/lib/jsf-nls.jar:/opt/IBM/WebSphere/AppServer/lib/lmproxy.jar:/opt/IBM/WebSphere/AppServer/lib/urlprotocols.jar:/opt/IBM/WebSphere/AppServer/deploytool/itp/batchboot.jar:/opt/IBM/WebSphere/AppServer/deploytool/itp/batch2.jar:/opt/IBM/WebSphere/AppServer/java/lib/tools.jar-Dibm.websphere.internalClassAccessMode=allow
-Xms50m
-Xmx256m
-Xcompressedrefs-Xscmaxaot12M-Xscmx90M
[dropped]

```

**Comment by arthurdm** [comment] 2018-10-09 12:48
thanks guys - I have opened https://github.com/WASdev/ci.docker.websphere-traditional/issues/98 to track this on the tWAS container side.

**Comment by recena** [comment] 2018-10-09 17:02
@arthurdm thanks so much.
