### ISSUE TITLE
springBoot2 liberty container with JAX-RS - Jersey results in ClassNotFoundException: javax.annotation.Priority

### ISSUE THREAD

**Issue by Jooones** [WASdev/ci.docker#182] opened 2018-08-23 10:28 UTC
Hi,

We use the websphere-liberty:springBoot2 image and to run our Spring Boot application which uses JAX-RS and Jersey for configuring our REST controllers.
When running the app directly in our IDE it works fine but when we try to run it using the specified docker image, it fails to start with the following problem: `ClassNotFoundException: javax.annotation.Priority` (See truncated stacktrace below).

We checked our Spring Boot jar and the Priority annotation class is there.
Opening the jar shows the following: application.jar/BOOT-INF/lib/javax.annotation-api-1.3.2.jar/javax/annotation/Priority.class

It seems like the classloader used does not look for the Priority class in our jar. 
Any idea why this is happening?

Does the websphere-liberty:springBoot2 image not support the JAX-RS - Spring combination?

```
2018-08-23 09:50:53.773  INFO 1 --- [ecutor-thread-2] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2574 ms
2018-08-23 09:50:53.867  WARN 1 --- [ecutor-thread-6] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Error occured initializing the ServletContext.
2018-08-23 09:50:53.892  INFO 1 --- [ecutor-thread-6] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-08-23 09:50:53.920 ERROR 1 --- [ecutor-thread-6] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Error occured initializing the ServletContext.
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:155) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
...
Caused by: java.lang.NoClassDefFoundError: javax.annotation.Priority
	at org.glassfish.jersey.model.internal.ComponentBag.modelFor(ComponentBag.java:551) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.model.internal.ComponentBag.lambda$registerModel$10(ComponentBag.java:477) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.model.internal.ComponentBag$$Lambda$343.0000000030070F00.call(Unknown Source) ~[na:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:316) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:298) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:229) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.model.internal.ComponentBag.registerModel(ComponentBag.java:469) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.model.internal.ComponentBag.register(ComponentBag.java:306) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.model.internal.CommonConfig.register(CommonConfig.java:408) ~[jersey-common-2.26.jar:na]
	at org.glassfish.jersey.server.ResourceConfig.register(ResourceConfig.java:422) ~[jersey-server-2.26.jar:na]
	... 44 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.annotation.Priority
	at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:504) ~[na:na]
	at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:276) ~[na:na]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:925) ~[na:2.9 (07-31-2018)]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:870) ~[na:2.9 (07-31-2018)]
	at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:482) ~[na:na]
	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:443) ~[na:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:853) ~[na:2.9 (07-31-2018)]
	... 55 common frames omitted
```

Kind regards,
Jooones

**Comment by dazavala** [comment] 2018-08-24 13:47
Hello. To date there are no published restrictions regarding the deployment of JAX-RS Spring Boot applications on springBoot2 (i.e. Liberty 18.0.0.2.)  The class loading error is puzzling.  Given your description I would expect the Priority class to be visible to the application class loader.  Perhaps the class is not in the lib.index.cache directory.  I'd like to determine this problem.  Do you mind attaching your application jar and dockerfile (if any), and telling us the command you used to start your docker container?

**Comment by Jooones** [comment] 2018-08-24 14:50
Hi,

See [SpringBootLibertyDocker.zip](https://github.com/WASdev/ci.docker/files/2318800/SpringBootLibertyDocker.zip) for the spring boot jar and Dockerfile.

Commands to execute:
- `docker build -t libertytestimage .`
- `docker run -p 8080:9080 libertytestimage`

This should reproduce the issue locally. 

The code which created the jar can be found at https://github.com/nielsjani/liberty-test.

Kind regards,
Jonathan

**Comment by Jooones** [comment] 2018-08-27 06:12
While searching the web for a possible cause of this issue, we found that the 'ClassNotFoundException: javax.annotation.Priority' error occurs a few times in combination with java 9.

Is it possible the SpringBoot2 container is run with java 9 and not java 8?
-> We are using java 8 to build the spring boot jar.

**Comment by dazavala** [comment] 2018-08-27 19:44
Hello @Jooones and thanks for your help. My suspicion was correct: the javax annotations dependency jar was removed from the deployment. But more importantly, the Liberty feature set declared within the springBoot tags' /config/server.xml directs the server to provision v1.1 of the annotations API, which lacks the Priority class required by your application. 

This problem is independent of whether the springBoot tags support JAX-RS(jersey)+Spring applications. We've definitely uncovered a bug here regarding the provision of API packages for Spring Boot applications, and I opened [issue 4853](https://github.com/OpenLiberty/open-liberty/issues/4853) to address the problem. 

To continue development you can alleviate the NCDFE by enabling an additional feature that provisions a compatible version of the annotations API. I attached a simple testDockerfile and testServer.xml that installs a feature and updates the server configuration over the springBoot layer along with your app [WASDev-ci.docker-182.27aug.zip](https://github.com/WASdev/ci.docker/files/2325031/WASDev-ci.docker-182.27aug.zip). 

Please note that any feature set that enables EJB support, either directly or indirectly, will result in [issue 4310](https://github.com/OpenLiberty/open-liberty/issues/4310). The fix for issue 4310 will release in Liberty 18.0.0.3.

**Comment by dazavala** [comment] 2018-08-27 20:14
Missed this while responding earlier: "Is it possible the SpringBoot2 container is run with java 9 and not java 8?" No sir. The problem is caused by the server provisioning an incompatible version of the javax.annotations package.

**Comment by dazavala** [comment] 2018-10-22 21:06
Hello @Jooones. Shall we close this issue? The fix for OpenLiberty-issue-4853 recently merged into master and will GA in Liberty 18.0.0.4, including the springBoot1(2) tags.  The fix causes Liberty to provision the most suitable level of the javax.annotations api for the servlet-3.1 and servlet-4.0 features -- i.e. 1.2 and 1.3 respectively.  For instance, the springBoot2 tag enables servlet-4.0, which in turn will cause Liberty to provision javax.annotations.api 1.3.  I **successfully** started your test application on a recent build of OpenLiberty over the feature set enabled in the springBoot2 tag -- i.e. springBoot-2.0, jsp-2.3, servlet-4.0, transportSecurity-1.0, and websocket-1.0. Thanks!

**Comment by Jooones** [comment] 2018-10-23 08:05
Hi @dazavala, ok for me to close. 
Thanks for the follow up.

**Comment by dazavala** [comment] 2018-10-23 14:00
Thanks!

**Comment by arthurdm** [comment] 2018-10-23 14:14
Thanks guys!

**Closed by arthurdm** 2018-10-23 14:14 UTC
Labels: spring
