### ISSUE TITLE
WAS Librety Kernel is not compatible with WebProfile 9.1

### ISSUE THREAD

**Issue by WojtekHenszke** [WASdev/ci.docker#479] opened 2022-10-31 10:40 UTC
It looks like feature com.ibm.websphere.appserver.builtinAuthentication-1.0 is somehow present in liberty Kernel image

To reproduce issue:
1. docker run -d --name was websphere-liberty:22.0.0.10-kernel-java11-openj9 && docker exec -it was bash
2. installUtility install webProfile-9.1 ( tried with `featureUtility if webProfile-9.1` as well)
3. add line <feature>webProfile-9.1</feature>  in file /opt/ibm/wlp/usr/servers/defaultServer/server.xml
```
default@199a5ea642ec:/$ cat /opt/ibm/wlp/usr/servers/defaultServer/server.xml
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">

  <!-- Enable features -->
  <featureManager>
    <feature>webProfile-9.1</feature>
  </featureManager>
  ```
4. restart container and observed in logs:
```
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKE0100I: This product is licensed for development, and limited production use. The full license terms can be viewed here: https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/license/base_ilan/ilan/22.0.0.10/lafiles/en.html
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ibm/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[ERROR   ] CWWKF0044E: The webProfile-9.1 and com.ibm.websphere.appserver.builtinAuthentication-1.0 features cannot be loaded at the same time. The webProfile-9.1 feature of Jakarta EE 9 is incompatible with the com.ibm.websphere.appserver.builtinAuthentication-1.0 feature of Java EE 6. The webProfile-9.1 and webProfile-9.1 configured features include an incompatible combination of features. Your configuration is not supported. Update the configuration to use features that support either the Jakarta EE or Java EE programming models, but not both.
[WARNING ] CWWKF0046W: The configuration includes an incompatible combination of features. As a result, the feature manager did not install any features.
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 0.808 seconds.
```

**Comment by idlewis** [comment] 2022-11-15 14:25
Only features which are listed in server.xml should be active when a server starts, so I think the issue isn't that the builtinAuthentication-1.0 is present in the image, it is that the webProfile-9.1 feature is somehow dependent on a feature which it is incompatible with. I will dig a bit further, but this is probably an issue with the features, not with the docker image itself

**Comment by WojtekHenszke** [comment] 2022-11-15 14:32
Hi i found that this is related to : https://github.com/OpenLiberty/open-liberty/issues/21992
And simple workaround for now is:

> changing installUtility invocation to be `installUtility install defaultServer` assuming that defaultServer is server name, should allow to install

**Comment by idlewis** [comment] 2022-11-15 14:42
@WojtekHenszke I'm glad you have a work around. Are you happy to close this issue? The websphere-liberty container will pick up any fixes from the next Liberty release, as soon as it is available.

**Closed** 2022-11-15 15:45 UTC
Labels: zenhub-dev
